"""SMA3 Constants
Non-pointer constants."""

crc32 = 0x40A48276

maxlevelID = 0x47
maxsublevelID = 0xF5
maxsublevelIDscreenexit = 0xFF
maxscreen = 0x7F
maxtileX = 0xFF
maxtileY = 0x7F

maxlayer1screens = 0x3F
maxspritecount = 0xFF
maxobjF0F3 = 0x13

levelnumrighthalf = ["1", "2", "3", "4", "5", "6", "7", "8",
                    "Secret", "Extra", "Bonus", "Controls"]

## Header setting constants

class _HeaderSetting:
    def __init__(self, name, index, maxvalue, default=0, shortname=None,
                 tooltip=None, isgraphics=False, ispalette=False):
        self.name = name
        self.index = index
        self.maxvalue = maxvalue
        self.default = default  # "None" value if one exists, else 0

        self.shortname = shortname if shortname is not None else self.name
        self.tooltip = ((self.shortname + "<br>" + tooltip)
                        if tooltip is not None else "")
        self.isgraphics = isgraphics
        self.ispalette = ispalette

        self._idnames = None

    @property
    def names(self):
        if self._idnames is not None:
            return self._idnames
        else:
            formatstr = "0" + str(len(f"{self.maxvalue:X}")) + "X"
            return [format(i, formatstr) for i in range(self.maxvalue + 1)]
    @names.setter
    def names(self, value):
        if len(value) <= self.maxvalue:
            raise ValueError(
                "Insufficient header names provided.\n"
                f"Expected length: {self.maxvalue+1 :#x}\n"
                f"Actual length: {len(value):#x}"
                )
        self._idnames = value

header = [
    _HeaderSetting("Background Color", 0, maxvalue=0x1F, ispalette=True,
        tooltip="""Affects the color or gradient behind all layers.
IDs 00-0F are solid colors, while 10+ are gradients."""),
    _HeaderSetting("Layer 1 Tileset", 1, maxvalue=0x0F, isgraphics=True,
        tooltip="""Affects graphics typically used by layer 1, the object
layer.
Also affects the tiles generated by many objects."""),
    _HeaderSetting("Layer 1 Palette", 2, maxvalue=0x1F, ispalette=True,
        tooltip="""Affects palette rows 4-5, and colors C-F of rows 1-3."""),
    _HeaderSetting("Layer 2 Image", 3, maxvalue=0x1F, isgraphics=True,
                   default=0x1B,
        tooltip="""Affects graphics and image loaded on layer 2, usually
the sublevel's background.
Certain layer 1 objects (e.g. train tracks) also use this setting."""),
    _HeaderSetting("Layer 2 Palette", 4, maxvalue=0x3F, ispalette=True,
        tooltip="""Affects palette rows 6-7."""),
    _HeaderSetting("Layer 3 Image", 5, maxvalue=0x2F, isgraphics=True,
        tooltip="""Affects graphics and image loaded on layer 3.
This may be an additional background layer, but has a variety of other purposes.
"""),
    _HeaderSetting("Layer 3 Palette", 6, maxvalue=0x3F, ispalette=True,
        tooltip="""Affects palette row 0, and sometimes rows 8-9."""),
    _HeaderSetting("Sprite Tileset", 7, maxvalue=0x95, isgraphics=True,
        tooltip="""Affects the 6 "stripes" of sprite graphics,
used by tileset-specific sprites."""),
    _HeaderSetting("Sprite Palette", 8, maxvalue=0x0F, ispalette=True,
        tooltip="""Affects palette rows 16-17."""),
    _HeaderSetting("Special Tileset", 9, maxvalue=0x0F,
                   default=4,
        tooltip="""Mostly an unused leftover from the SNES version.
Still used to load the Raphael arena (9) and Kamek block room (A)."""),
    _HeaderSetting("Graphics Animation", 0xA, maxvalue=0x12, isgraphics=True,
        tooltip="""Animates 8x8 tiles for various purposes.
To avoid slowdown, Advynia only depicts a single frame of the animation."""),
    _HeaderSetting("Palette Animation", 0xB, maxvalue=0x14, ispalette=True,
        tooltip="""Animates palette colors for various purposes.
<br><i>Unimplemented</i>"""),
    _HeaderSetting("Layer 2/3 Scroll", 0xC, maxvalue=0x1F,
        tooltip="""Determines the scrolling speed of layers 2 and 3."""),
    _HeaderSetting("Header Music", 0xD, maxvalue=0x0F,
        tooltip="""Affects the sublevel's music. Boss-related music also
disables pause menu items."""),
    _HeaderSetting("Item Memory Index/\nMiddle Ring ID", 0xE, maxvalue=3,
        shortname="Item Memory Index",
        tooltip="""Affects how the game tracks collected items. This should
be set to a unique value per sublevel, if possible.<br>
Also determines the midway entrance number, for any Middle Ring in this
sublevel."""),
    ]

# header subset for palettes
headerpalettes = [_setting for _setting in header if _setting.ispalette]
# header subset for graphics
headergraphics = [_setting for _setting in header if _setting.isgraphics]

_headernames = {
    0x01: [
        "Cave + background walls",
        "Grass + background walls",
        "Submarine",
        "2.5D + Hookbill blocks",
        "Snow",
        "Jungle",
        "Castle (striped)",
        "Meadow + background walls",
        "Cave + mushrooms/ice/lava",
        "Grass + Forest",
        "Castle (wooden)",
        "Sewer",
        "Flower",
        "Meadow + clouds/bridges",
        "Castle (stone)",
        "Meadow + line-guides",
        "",
        "W6 Wasteland",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        ],
    0x03: [
        "Cave waterfalls/lavafalls",
        "Tree trunks and bushes",
        "Submarine BG",
        "2.5D lava room (L1=3)",
        "Mountains, trees, hills",
        "Distant fog-shrouded evergreens",
        "Castle wall with torches",
        "Vertical-sided hills",
        "Forest with flowering canopy",
        "(same as 10)",
        "Trees and waterfalls",
        "Grassy platforms (A=02/0B)",
        "Forest with straight canopy",
        "Starry sky with moon",
        "Spiral-decorated platforms",
        "Volcanoes (A=02/0B)",
        "Mountains with forest in front",
        "(glitch)",
        "Sea with clouds",
        "Cave with crystals",
        "Building interior with windows",
        "Snowcapped mountains",
        "Layer 2 boss graphics",
        "(glitch)",
        "Jungle interior with windows",
        "Castle ramparts",
        "Snowcapped cloudy mountains",
        "None",
        "Smiley hills",
        "Rounded mountains (A=02/0B)",
        "Evergreen forest",
        "Baby Bowser's room",
        ],
    0x05: [
        "None",
        "Submarine water (A=01)",
        "Layer 3 sprites, default",
        "(glitch)",
        "Smiley clouds (A=03/11)",
        "Layer 3 sprites, left shadow",
        "Layer 3 sprites, striped",
        "(same as 02)",
        "(same as 02)",
        "?",
        "FG hides land BG walls (L1=?)",
        "?",
        "Diagonal light beams",
        "Tall clouds?",
        "?",
        "?",
        "?",
        "Pre-Hookbill mist",
        "Starry sky",
        "Interactive wavy water (A=05)",
        "Foreground canopy/vines",
        "Foreground crystals",
        "Shark Chomp (sprite 154)",
        "?",
        "Castle ramparts (A=06)",
        "Snowing foreground (A=09)",
        "Clouds/Goonies (A=0A)",
        "FG flowers (butterfly A=0B)",
        "Dark room + Yoshi light circle",
        "(13 but higher water, glitched)",
        "Large moon (variant)",
        "SNES Kamek color wash?",
        "Bushes/clouds (A=0F)",
        "Froggy interior",
        "Clouds, replaces BG color",
        "Sunset (A=0F)",
        "Moon/stars with auras",
        "Castle windows/lights",
        "Bigger Boo/Milde explosion",
        "?",
        "Small stars?",
        "Large clouds (variant)",
        "Large moon",
        "Large clouds (variant)",
        "Foreground mist",
        "Foreground mist, moving left",
        "Large clouds (variant)",
        "?",
        ],
    0x07: [
        "Stripes 20 21 2A 2B 5E 29",
        "Stripes 20 21 5E 1C 31 29",
        "Stripes 1F 2C 36 40 51 29",
        "Stripes 2E 5E 37 1A 1A 1F",
        "Stripes 55 5E 5F 1F 1A 29",
        "Stripes 53 40 51 1A 1A 29",
        "Stripes 36 2A 2B 3C 2D 71",
        "Stripes 4A 36 1C 71 31 59",
        "Stripes 6A 1A 1A 1A 1A 1A",
        "Stripes 50 71 2F 31 49 29",
        "Stripes 55 57 5D 71 1C 2F",
        "Stripes 55 71 3C 57 4A 1C",
        "Stripes 3C 3F 1F 71 1A 1A",
        "Stripes 25 71 1C 1A 1A 1A",
        "Stripes 2E 1A 1A 1A 1A 1F",
        "Stripes 36 57 38 1C 5C 29",
        "Stripes 3A 3B 31 55 71 29",
        "Stripes 60 61 1C 22 23 25",
        "Stripes 1C 25 42 43 4F 29",
        "Stripes 5A 5B 5C 25 6A 29",
        "Stripes 1F 37 39 42 43 1A",
        "Stripes 27 35 4E 3D 1A 30",
        "Stripes 4E 1C 51 46 71 29",
        "Stripes 22 23 45 60 1A 30",
        "Stripes 42 43 38 39 1C 59",
        "Stripes 60 1D 71 4E 1C 30",
        "Stripes 60 1D 40 46 4E 30",
        "Stripes 55 1D 60 4E 51 1A",
        "Stripes 36 63 1F 5C 1A 29",
        "Stripes 39 1D 35 1B 63 30",
        "Stripes 71 1A 51 5F 60 30",
        "Stripes 2A 63 1A 1A 1A 1A",
        "Stripes 27 3E 1A 3D 1A 1A",
        "Stripes 25 2B 47 64 36 1F",
        "Stripes 51 61 48 65 1C 60",
        "Stripes 48 1C 65 28 60 71",
        "Stripes 1C 45 1F 71 6A 29",
        "Stripes 4D 6A 48 1F 1A 29",
        "Stripes 28 60 38 4E 36 51",
        "Stripes 1A 1A 2D 1A 1A 1A",
        "Stripes 45 35 54 64 1F 1C",
        "Stripes 54 58 35 3D 71 64",
        "Stripes 35 41 1F 64 5C 1C",
        "Stripes 32 33 34 41 4C 54",
        "Stripes 64 1E 41 1F 1C 29",
        "Stripes 55 1E 28 60 71 5C",
        "Stripes 64 4C 41 40 68 29",
        "Stripes 2F 5C 5D 1C 1A 1A",
        "Stripes 27 65 49 AA 1C 1F",
        "Stripes 61 48 71 1C 55 6A",
        "Stripes 71 3C 60 3F 49 AA",
        "Stripes 53 1A 1C 55 31 59",
        "Stripes 42 43 55 1F 41 1A",
        "Stripes 2A 2B 29 71 1C 5D",
        "Stripes 55 1F 27 2A 1A 29",
        "Stripes 4F 2B 47 52 60 51",
        "Stripes 2B 47 38 71 60 51",
        "Stripes 40 29 31 4E 1C 59",
        "Stripes 1C 1A 1A 4E 1A 1A",
        "Stripes 2B 47 26 52 56 29",
        "Stripes 2B 47 26 52 31 29",
        "Stripes 2B 47 1F 29 31 51",
        "Stripes 2B 47 2F 1E 71 29",
        "Stripes 29 1A 1A 53 1B 1F",
        "Stripes 31 40 1F 1A 1A 1A",
        "Stripes 41 35 39 71 1F 29",
        "Stripes 2B 47 24 49 1A 1F",
        "Stripes 1F 5C 49 4E 5D 47",
        "Stripes 3A 3B 1C 1A 1A 29",
        "Stripes 1F 1A 38 1A 1A 1A",
        "Stripes 2B 47 37 54 71 29",
        "Stripes 3F 3C 66 1C 47 60",
        "Stripes 31 35 71 54 55 1F",
        "Stripes 2E 1F 49 24 5E 29",
        "Stripes 58 54 5E 1F 48 29",
        "Stripes 60 65 30 71 1A 1A",
        "Stripes 5E 29 71 26 49 4B",
        "Stripes 55 2F 58 64 2C 59",
        "Stripes 5E 24 1C 29 49 4B",
        "Stripes 27 25 38 49 2A 29",
        "Stripes 1F 36 4E 1A 1A 1A",
        "Stripes 4D 1F 55 28 60 71",
        "Stripes 2E 71 1C 1A 1A 1A",
        "Stripes 35 39 41 25 64 29",
        "Stripes 64 25 36 41 1A 29",
        "Stripes 4E 44 1A 3D 48 29",
        "Stripes 5D 1E 36 3D 25 48",
        "Stripes 42 43 44 6A 1A 1A",
        "Stripes 64 45 1A 1A 1F 29",
        "Stripes 2A 2B 38 6A 6C 5E",
        "Stripes 55 31 1A 1A 1A 1F",
        "Stripes 35 3E 1C 3D 2B 47",
        "Stripes 2A 2B 5E 63 1A 1A",
        "Stripes 24 1A 1A 1A 1A 1A",
        "Stripes 1A 36 31 29 66 59",
        "Stripes 40 3A 3B 37 36 1A",
        "Stripes 2F 70 61 6A 1A 1F",
        "Stripes 6B 6C 1A 6A 47 1F",
        "Stripes 57 5C 5D 24 1C 29",
        "Stripes 1B 71 29 1C 1F 5D",
        "Stripes 55 5C 5F 45 71 37",
        "Stripes 6F 6D 6E 29 6A 1A",
        "Stripes 55 6A A9 1A 1A 1F",
        "Stripes 62 3C 4E 53 71 44",
        "Stripes 68 6A 1A 1A 1A 1A",
        "Stripes 1A 1E 52 1F 71 29",
        "Stripes 5D 44 4C 56 1A 1A",
        "Stripes 1C 29 44 2A 71 4E",
        "Stripes 45 71 1C 58 1A 1A",
        "Stripes 55 25 71 1F 29 1C",
        "Stripes 5D 37 71 29 1C 1A",
        "Stripes 45 6A 1F 1A 1A 1A",
        "Stripes 1F 64 41 53 3E 1C",
        "Stripes 53 71 5D 1C 1A 1A",
        "Stripes 36 1C 38 28 60 29",
        "Stripes 2B 47 20 21 1C 71",
        "Stripes 20 21 2F 1C 5D 47",
        "Stripes 27 35 41 54 64 68",
        "Stripes 1C 71 2C 2D 1A 1A",
        "Stripes 6A 6C 63 1A 1A 1A",
        "Stripes 22 23 45 60 1A 30",
        "Stripes 67 3C 55 1A 1A 29",
        "Stripes 54 71 41 4C 64 37",
        "Stripes AD AE AF B0 67 6A",
        "Stripes 55 47 57 49 1C 29",
        "Stripes 27 2B 47 1C 25 29",
        "Stripes 27 71 1C 31 1A 1A",
        "Stripes 1C 45 1F 71 46 29",
        "Stripes 20 21 1C 71 36 1C",
        "Stripes 20 21 4C 51 71 29",
        "Stripes 55 47 51 4E 1C 1C",
        "Stripes 51 31 38 2A 46 1C",
        "Stripes 47 1D 29 59 1C 1D",
        "Stripes 35 68 1F 29 1C 1C",
        "Stripes 35 3E 1A 3D 1A 1A",
        "Stripes 2E 1C 1C 71 1C 1C",
        "Stripes 1A 1E 1A 1A 1A 29",
        "Stripes 2B 47 1C 1A 31 1A",
        "Stripes 2B 47 37 71 1C 1C",
        "Stripes 2B 47 1A 52 31 1C",
        "Stripes 2B 47 1C 1A 31 1A",
        "Stripes 27 5D 1C 4E 71 29",
        "Stripes 27 51 45 4E 71 29",
        "Stripes 27 5E 37 2E 1C 29",
        "Stripes 59 31 26 56 35 29",
        "Stripes 66 45 30 51 31 1C",
        "Stripes 27 57 38 4E 1C 1C",
        "Stripes 3A 3B 1C 71 1C 1C",
        "Stripes 1F 64 38 5C 1C 1C",
        "Stripes 20 21 5E 1C 6A 6C",
        ],
    0x09: [
        "None",
        "None?",
        "None?",
        "None?",
        "None?",
        "None?",
        "? for L3=2C",
        "None?",
        "None?",
        "Raphael's moon",
        "Kamek block room",
        "None?",
        "None?",
        "Froggy interior FG star count",
        "None?",
        "None?",
        ],
    0x0A: [
        "None (clear animated region)",
        "Water for L3=01",
        "Clouds for L2=0B/0F/1D",
        "Smiley clouds for L3=04",
        "None (do nothing)",
        "Water waves for L3=13",
        "Torches for L3=18/?",
        "Lava for object 47",
        "Water for object DC",
        "Foreground snow for L3=19",
        "Goonies for L3=1A",
        "Butterfly for L3=1B + 02's clouds",
        "Water for object 35",
        "Animations 06+07",
        "Animations 06+0C",
        "Clouds for L3=20/23",
        "(glitch)",
        "Animations 03+0C",
        "2.5D lava for object FE",
        ],
    0x0B: [
        "None",
        "??? for Raphael battle",
        "?",
        "Torches for L2=06?",
        "Waterfalls for L2=0A?",
        "Cave crystal sparkles?",
        "Cave crystal sparkles?",
        "(unused)",
        "Sewer water flow?",
        "Torches for L2=09?",
        "(unused)",
        "Snow for L3=19?",
        "Snow for L3=19?",
        "Sunset for L3=23?",
        "Water/lavafalls for L2=00?",
        "Lantern aura for L3=25",
        "Mist for L3=2C?",
        "Water/lavafalls + mist?",
        "??? + mist?",
        "Water/lavafalls + light for L3=0C?",
        "(same as 13)",
        ],
    }
for key, names in _headernames.items():
    header[key].names = names

# flags for whether each layer 2/3 ID is a background/foreground image (display)
#  or another purpose (don't display)
layer23enable = {
    2: [
        1, 1, 1, 1, 1, 1, 1, 1,  # 00-07
        1, 1, 1, 1, 1, 1, 1, 1,  # 08-0F
        1, 1, 1, 1, 1, 1, 0, 1,  # 10-17
        1, 1, 1, 1, 1, 1, 1, 1,  # 18-1F
        ],
    3: [
        1, 1, 0, -1, 1, 0, 0, 0,  # 00-07
        0, -1, 0, 0, 1, 1, 1, 1,  # 08-0F
        1, -1, 1, 1, 1, 1, 0, -1,  # 10-17
        1, -1, -1, 1, 0, -1, -1, 0,  # 18-1F
        1, 1, 1, 1, 1, 1, 0, 1,  # 20-27
        1, 1, -1, 1, 1, 1, 1, 1,  # 28-2F
        ],
    }

entranceanim = [
    "None / X door closing",
    "On skis",
    "Pipe, rightward",
    "Pipe, leftward",
    "Pipe, downward",
    "Pipe, upward",
    "Screen edge, rightward",
    "Screen edge, leftward",
    "Screen edge, downward",
    "Launch upward",
    "Raphael's moon",
    ]

banditminigames = [
    "Throwing Balloons (4)",
    "Throwing Balloons (5)",
    "Throwing Balloons (6)",
    "",
    "Gather Coins",
    "Popping Balloons (+10)",
    "Popping Balloons (+20)",
    "",
    "",
    "Seed Spitting Contest",
    ]

stripes = [
    (0x1A, "Hookbill BG/null stripe"),
    (0x1B, "Chomps, BG Shy Guy, Raphael (1/2)"),
    (0x1C, "Red arrows, Raphael (2/2)"),
    (0x1D, "Zeus Guy"),
    (0x1E, "Melon Bug, Harry Hedgehog"),
    (0x1F, "Egg Plant, Barney Bubble"),
    (0x20, "Falling stone block (1/2)"),
    (0x21, "Falling stone block (2/2)"),
    (0x22, "Boo Blah (1/2)"),
    (0x23, "Boo Blah (2/2)"),
    (0x24, "Heading Pokey"),
    (0x25, "Nipper Plant, Gusty (long horizontal)"),
    (0x26, "Spike (enemy), Goomba"),
    (0x27, "Huffin Puffin, Stretch Shy Guy"),
    (0x28, "Little Mouser"),
    (0x29, "Milde, Piranha Plant, Tap-Tap"),
    (0x2A, "Goonie, rotation block"),
    (0x2B, "Wings for Paratroopa/Goonie"),
    (0x2C, "Gusty (vertical back and forth)"),
    (0x2D, "Gusty (horizontal back and forth)"),
    (0x2E, "Ski Lift, Train Shy Guy"),
    (0x2F, "Eggo-Dil, giant egg"),
    (0x30, "Blindfold Boo, Pyro Guy"),
    (0x31, "Bullet Bill, rotating doors 1-2"),
    (0x32, "Lunge Fish (1/3)"),
    (0x33, "Lunge Fish (2/3)"),
    (0x34, "Lunge Fish (3/3)"),
    (0x35, "Spear Guy (shielded), Clawdaddy"),
    (0x36, "Blow Hard, Spiked Fun Guy"),
    (0x37, "Stilt Guy"),
    (0x38, "Baseball Boys"),
    (0x39, "Spear Guy (dancing)"),
    (0x3A, "Poochy (1/2)"),
    (0x3B, "Poochy (2/2)"),
    (0x3C, "Boo Guy (working)"),
    (0x3D, "Boo Guy (relay)"),
    (0x3E, "Submarine enemies"),
    (0x3F, "Boo Guy (raising a spiked ball)"),
    (0x40, "Snifit, rotating doors 3-4"),
    (0x41, "Georgette Jelly"),
    (0x42, "Large ghosts (1/2)"),
    (0x43, "Large ghosts (2/2)"),
    (0x44, "Flower pot"),
    (0x45, "Slime Drop, Salvo, various eyes"),
    (0x46, "Spooky Shy Guy, Grim Leecher"),
    (0x47, "Koopa"),
    (0x48, "Boo (1x1), buoyant post, keyhole cork"),
    (0x49, "Lakitu"),
    (0x4A, "Kaboomba"),
    (0x4B, "Thunder Lakitu"),
    (0x4C, "Buoyant grassy platform, Donut Lift"),
    (0x4D, "Tap-Tap the Red Nose/Golden"),
    (0x4E, "Bandit, spiked weight for ? gear"),
    (0x4F, "Raven (wall-following), Aqua Lakitu"),
    (0x50, "Fat Guy"),
    (0x51, "Lava Drop"),
    (0x52, "Fuzzy"),
    (0x53, "Nep-Enut, Shark Chomp, Ghost lift 5-4"),
    (0x54, "Cheep-Cheep"),
    (0x55, "Lantern Ghost, Sluggy, Fang"),
    (0x56, "Flutter"),
    (0x57, "Arrow clouds"),
    (0x58, "Spray Fish"),
    (0x59, "Grunt, Mace Guy"),
    (0x5A, "Naval Piranha vines (1/2)"),
    (0x5B, "Naval Piranha vines (2/2)"),
    (0x5C, "Vine from winged cloud"),
    (0x5D, "Petal Guy, Crazee Dayzee"),
    (0x5E, "Bumpty, bird decoration"),
    (0x5F, "Falling icicle"),
    (0x60, "Boo Guy, Little Mouser (skull mask)"),
    (0x61, "Boo (2x2)"),
    (0x62, "Blargg"),
    (0x63, "Skeleton Goonie"),
    (0x64, "Monkey"),
    (0x65, "Firebar, Boo Balloon, pumpable balloon"),
    (0x66, "Hot Lips"),
    (0x67, "Kamek (standing, geometric magic)"),
    (0x68, "Frog Pirate"),
    (0x69, "(unused monkey)"),
    (0x6A, "Kamek (flying/talking)"),
    (0x6B, "Hookbill (1/2)"),
    (0x6C, "Hookbill (2/2), background Kamek"),
    (0x6D, "2x2 Milde (1/2)"),
    (0x6E, "2x2 Milde (2/2)"),
    (0x6F, "4x4 Milde"),
    (0x70, "Prince Froggy battle"),
    (0x71, "Special Flower, tileset-specific"),
    (0xA9, "Sluggy the Unshaven?"),
    (0xAA, "Fishing Lakitu's rod"),
    (0xAB, "Intro Yoshis (1/2)"),
    (0xAC, "Intro Yoshis (2/2)"),
    (0xAD, "Baby Bowser (1/4)"),
    (0xAE, "Baby Bowser (2/4)"),
    (0xAF, "Baby Bowser (3/4)"),
    (0xB0, "Baby Bowser (4/4)"),
    ]

music = [
    "Story intro",
    "SMA3 title",
    "Choose a game",
    "YI title (W1-W5)",
    "YI title (W6/postgame)",
    "Intro cutscene",
    "Intro level",
    "Level select (W1)",
    "Level select (W2)",
    "Level select (W3)",
    "Level select (W4)",
    "Level select (W5)",
    "Level select (W6)",
    "Level select (postgame)",
    "Level intro drums",
    "Land level",
    "Jungle level",
    "Sky level",
    "Cave level",
    "Castle level",
    "Kamek encounter",
    "Kamek enlarge",
    "x-4 boss",
    "Pre-boss",
    "x-8 boss",
    "x-8 victory",
    "Bowser battle",
    "Bowser battle victory",
    "Kamek exits/ending",
    "Credits",
    "Credits end",
    "Bonus/Super Star",
    "Goal/x-4 victory",
    "Course clear",
    "Goal minigame",
    "Death (Yoshi died)",
    "Death (Toadies)",
    "Game over",
    "100% cutscene, part 1",
    "100% cutscene, part 2",
    ]

## Object/16x16 tile constants

# 16x16 tile interaction data, extra byte lookup
tile16interact_extra = {
    0x00: "No additional properties",
    0x01: "Sewer door",
    0x08: "Snowy in tileset 4???",
    0x10: "?",
    0x18: "Yellow sticky-ceiling platform",
    0x20: "Mud",
    0x28: "Instant death (fire)",
    0x30: "Coin",
    0x38: "Egg block",
    0x40: "Breakable dirt",
    0x48: "Train track",
    0x50: "(unused)",
    0x58: "Poundable post",
    0x60: "Red stairs, slope +1",
    0x68: "Red stairs, slope -1",
    0x70: "Large stone block, unstable",
    0x78: "! block",
    0x80: "Super Star block",
    0x88: "Donut Lift",
    0x90: "Countdown platform",
    0x98: "Flowing water",
    0xA0: "Enterable pipe",
    0xA8: "Snowy tree",
    0xB0: "! switch coin",
    0xB8: "Slippery",
    0xC0: "Rock spire, unstable",
    0xC8: "Spiked post",
    0xD0: "Icicle",
    0xD8: "Instant death (spikes)",
    0xE0: "?",
    }
# 16x16 tile special hardcoded interaction
tile16interact_special_highbyte = {
    0x7A: "Breakout block",
    0x7B: "Breakable castle block",
    0x87: "Line-guide",
    }
tile16interact_special_full = {
    0x0010: "Wall Lakitu spawn tile",
    0x9D8B: "Kamek block",
    }

# Tileset-specific tile data used by various object functions.
# Consists of a high byte, low byte length, and tileset-indexed tile IDs.
# (In-game, these constants are stored in the RAM table at 0200800C, generated
# from 081BC6E8.)

objdyntable = (
    (0x02, 0x04, (0x0200,0x0200,0x0200,0x0200,0x0208,0x0200,0x0210,0x020C,
                  0x0204,0x0200,0x0210,0x0200,0x0208,0x0200,0x0210,0x020C)),
    (0x03, 0x05, (0x0300,0x0300,0x0300,0x0300,0x030A,0x0300,0x0314,0x030F,
                  0x0305,0x0300,0x0314,0x0300,0x030A,0x0300,0x0314,0x030F)),
    (0x04, 0x01, (0x0400,0x0400,0x0400,0x0400,0x0402,0x0400,0x0403,0x0400,
                  0x0401,0x0400,0x0403,0x0400,0x0402,0x0400,0x0403,0x0400)),
    (0x05, 0x04, (0x0500,0x0500,0x0500,0x0500,0x0508,0x0500,0x0510,0x050C,
                  0x0504,0x0500,0x0510,0x0500,0x0508,0x0500,0x0510,0x050C)),
    (0x06, 0x05, (0x0600,0x0600,0x0600,0x0600,0x060A,0x0600,0x0614,0x060F,
                  0x0605,0x0600,0x0614,0x0600,0x060A,0x0600,0x0614,0x060F)),
    (0x07, 0x01, (0x0700,0x0700,0x0700,0x0700,0x0702,0x0700,0x0703,0x0700,
                  0x0701,0x0700,0x0703,0x0700,0x0702,0x0700,0x0703,0x0700)),
    (0x08, 0x09, (0x0809,0x0800,0x0800,0x0800,0x0812,0x0800,0x0824,0x081B,
                  0x0809,0x0800,0x0824,0x082D,0x0812,0x0836,0x0824,0x081B)),
    (0x09, 0x01, (0x0901,0x0900,0x0900,0x0900,0x0902,0x0900,0x0904,0x0903,
                  0x0901,0x0900,0x0904,0x0900,0x0902,0x0900,0x0904,0x0903)),
    (0x0A, 0x09, (0x0A09,0x0A00,0x0A00,0x0A00,0x0A12,0x0A00,0x0A24,0x0A1B,
                  0x0A09,0x0A00,0x0A24,0x0A2D,0x0A12,0x0A36,0x0A24,0x0A1B)),
    (0x0B, 0x01, (0x0B01,0x0B00,0x0B00,0x0B00,0x0B02,0x0B00,0x0B04,0x0B03,
                  0x0B01,0x0B00,0x0B04,0x0B00,0x0B02,0x0B00,0x0B04,0x0B03)),
    (0x0C, 0x05, (0x0C05,0x0C00,0x0C00,0x0C00,0x0C0A,0x0C00,0x0C14,0x0C0F,
                  0x0C05,0x0C00,0x0C14,0x0C00,0x0C0A,0x0C1E,0x0C14,0x0C0F)),
    (0x0D, 0x06, (0x0D06,0x0D00,0x0D00,0x0D00,0x0D0C,0x0D00,0x0D18,0x0D12,
                  0x0D06,0x0D00,0x0D18,0x0D00,0x0D0C,0x0D24,0x0D18,0x0D12)),
    (0x0E, 0x01, (0x0E01,0x3940,0x3940,0x3940,0x0E02,0x3940,0x0E04,0x0E03,
                  0x0E01,0x3940,0x0E04,0x3940,0x0E02,0x3940,0x0E04,0x0E03)),
    (0x0F, 0x07, (0x0F07,0x0F00,0x0F00,0x0F00,0x0F0E,0x0F00,0x0F1C,0x0F15,
                  0x0F07,0x0F00,0x0F1C,0x0F00,0x0F0E,0x0F2A,0x0F1C,0x0F15)),
    (0x10, 0x06, (0x1006,0x1000,0x1000,0x1000,0x100C,0x1000,0x1018,0x1012,
                  0x1006,0x1000,0x1018,0x1000,0x100C,0x1024,0x1018,0x1012)),
    (0x11, 0x01, (0x1101,0x1100,0x1100,0x1100,0x1102,0x1100,0x1104,0x1103,
                  0x1101,0x1100,0x1104,0x1100,0x1102,0x1100,0x1104,0x1103)),
    (0x12, 0x01, (0x1201,0x1200,0x1200,0x1200,0x1202,0x1200,0x1204,0x1203,
                  0x1201,0x1200,0x1204,0x1200,0x1202,0x1200,0x1204,0x1203)),
    (0x13, 0x01, (0x1301,0x1300,0x1300,0x1300,0x1302,0x1300,0x1304,0x1303,
                  0x1301,0x1300,0x1304,0x1300,0x1302,0x1300,0x1304,0x1303)),
    (0x1A, 0xBF, (0x1A00,0x1B00,0x1B00,0x1B00,0x1B00,0x1B00,0x1B00,0x1C00,
                  0x1A00,0x1B00,0x1B00,0x1B00,0x1B00,0x1B00,0x1B00,0x1C00)),
    (0x19, 0x32, (0x1900,0x1D00,0x1D00,0x1D00,0x1D00,0x1D00,0x1D00,0x7000,
                  0x1900,0x1D00,0x1D00,0x1D00,0x1D00,0x1D00,0x1D00,0x7000)),
    (0x1E, 0x01, (0x1E00,0x1E01,0x1E00,0x1E00,0x1E00,0x1E00,0x1E00,0x1E01,
                  0x1E00,0x1E01,0x1E00,0x1E00,0x1E00,0x1E00,0x1E00,0x1E01)),
    (0x1F, 0x02, (0x1F00,0x1F02,0x1F00,0x1F00,0x1F00,0x1F00,0x1F00,0x1F02,
                  0x1F00,0x1F02,0x1F00,0x1F00,0x1F00,0x1F00,0x1F00,0x1F02)),
    (0x20, 0x01, (0x2000,0x2001,0x2000,0x2000,0x2000,0x2000,0x2000,0x2001,
                  0x2000,0x2001,0x2000,0x2000,0x2000,0x2000,0x2000,0x2001)),
    (0x21, 0x01, (0x2100,0x2101,0x2100,0x2100,0x2100,0x2100,0x2100,0x2101,
                  0x2100,0x2101,0x2100,0x2100,0x2100,0x2100,0x2100,0x2101)),
    (0x22, 0x01, (0x2200,0x2201,0x2200,0x2200,0x2200,0x2200,0x2200,0x2201,
                  0x2200,0x2201,0x2200,0x2200,0x2200,0x2200,0x2200,0x2201)),
    (0x23, 0x01, (0x2300,0x2301,0x2300,0x2300,0x2300,0x2300,0x2300,0x2301,
                  0x2300,0x2301,0x2300,0x2300,0x2300,0x2300,0x2300,0x2301)),
    (0x24, 0x01, (0x2400,0x2401,0x2400,0x2400,0x2400,0x2400,0x2400,0x2401,
                  0x2400,0x2401,0x2400,0x2400,0x2400,0x2400,0x2400,0x2401)),
    (0x25, 0x01, (0x2500,0x2501,0x2500,0x2500,0x2500,0x2500,0x2500,0x2501,
                  0x2500,0x2501,0x2500,0x2500,0x2500,0x2500,0x2500,0x2501)),
    (0x26, 0x01, (0x2600,0x2601,0x2600,0x2600,0x2600,0x2600,0x2600,0x2601,
                  0x2600,0x2601,0x2600,0x2600,0x2600,0x2600,0x2600,0x2601)),
    (0x27, 0x01, (0x2700,0x2701,0x2700,0x2700,0x2700,0x2700,0x2700,0x2701,
                  0x2700,0x2701,0x2700,0x2700,0x2700,0x2700,0x2700,0x2701)),
    (0x28, 0x01, (0x2800,0x2801,0x2800,0x2800,0x2800,0x2800,0x2800,0x2801,
                  0x2800,0x2801,0x2800,0x2800,0x2800,0x2800,0x2800,0x2801)),
    (0x2A, 0x0F, (0x2A0F,0x2A00,0x2A00,0x2A00,0x2A1E,0x2A00,0x2A00,0x2A2D,
                  0x2A0F,0x2A00,0x2A00,0x2A00,0x2A1E,0x2A00,0x2A00,0x2A2D)),
    (0x38, 0x0C, (0x380C,0x3800,0x3800,0x3800,0x3818,0x3800,0x3800,0x3824,
                  0x380C,0x3800,0x3800,0x3800,0x3818,0x3848,0x3800,0x3824)),
    (0x39, 0x40, (0x3E00,0x3900,0x3900,0x3900,0x3A00,0x3900,0x3900,0x6E00,
                  0x3E00,0x3900,0x3900,0x3900,0x3A00,0x3900,0x3900,0x6E00)),
    (0x3B, 0x0F, (0x3B0F,0x3B00,0x3B00,0x3B00,0x3B1E,0x3B00,0x3B00,0x3B2D,
                  0x3B0F,0x3B00,0x3B00,0x3B00,0x3B1E,0x3B00,0x3B00,0x3B2D)),
    (0x3F, 0x05, (0x3F05,0x3F00,0x3F00,0x3F00,0x3F00,0x3F00,0x3F00,0x3F0A,
                  0x3F05,0x3F00,0x3F00,0x3F00,0x3F00,0x3F00,0x3F00,0x3F0A)),
    (0x40, 0x01, (0x4001,0x4000,0x4000,0x4000,0x4000,0x4000,0x3000,0x4002,
                  0x4001,0x4000,0x4000,0x4000,0x4000,0x4000,0x3000,0x4002)),
    (0x41, 0x01, (0x4101,0x4100,0x4100,0x4100,0x4100,0x4100,0x4100,0x4102,
                  0x4101,0x4100,0x4100,0x4100,0x4100,0x4100,0x4100,0x4102)),
    (0x42, 0x01, (0x4201,0x4200,0x4200,0x4200,0x4200,0x4200,0x4200,0x4202,
                  0x4201,0x4200,0x4200,0x4200,0x4200,0x4200,0x4200,0x4202)),
    (0x43, 0x01, (0x4301,0x4300,0x4300,0x4300,0x4300,0x4300,0x4300,0x4302,
                  0x4301,0x4300,0x4300,0x4300,0x4300,0x4300,0x4300,0x4302)),
    (0x44, 0x01, (0x4401,0x4400,0x4400,0x4400,0x4400,0x4400,0x4400,0x4402,
                  0x4401,0x4400,0x4400,0x4400,0x4400,0x4400,0x4400,0x4402)),
    (0x45, 0x01, (0x4501,0x4500,0x4500,0x4500,0x4500,0x4500,0x4500,0x4502,
                  0x4501,0x4500,0x4500,0x4500,0x4500,0x4500,0x4500,0x4502)),
    (0x46, 0x01, (0x4601,0x4600,0x4600,0x4600,0x4600,0x4600,0x4600,0x4602,
                  0x4601,0x4600,0x4600,0x4600,0x4600,0x4600,0x4600,0x4602)),
    (0x47, 0x01, (0x4701,0x4700,0x4700,0x4700,0x4700,0x4700,0x4700,0x4702,
                  0x4701,0x4700,0x4700,0x4700,0x4700,0x4700,0x4700,0x4702)),
    (0x48, 0x01, (0x4801,0x4800,0x4800,0x4800,0x4800,0x4800,0x4800,0x4802,
                  0x4801,0x4800,0x4800,0x4800,0x4800,0x4800,0x4800,0x4802)),
    (0x49, 0x01, (0x4901,0x4900,0x4900,0x4900,0x4900,0x4900,0x4900,0x4902,
                  0x4901,0x4900,0x4900,0x4900,0x4900,0x4900,0x4900,0x4902)),
    (0x4A, 0x01, (0x4A01,0x4A00,0x4A00,0x4A00,0x4A00,0x4A00,0x4A00,0x4A02,
                  0x4A01,0x4A00,0x4A00,0x4A00,0x4A00,0x4A00,0x4A00,0x4A02)),
    (0x4B, 0x01, (0x4B01,0x4B00,0x4B00,0x4B00,0x4B00,0x4B00,0x4B00,0x4B02,
                  0x4B01,0x4B00,0x4B00,0x4B00,0x4B00,0x4B00,0x4B00,0x4B02)),
    (0x4C, 0x01, (0x4C01,0x4C00,0x4C00,0x4C00,0x4C00,0x4C00,0x4C00,0x4C02,
                  0x4C01,0x4C00,0x4C00,0x4C00,0x4C00,0x4C00,0x4C00,0x4C02)),
    (0x4D, 0x01, (0x4D01,0x4D00,0x4D00,0x4D00,0x4D00,0x4D00,0x4D00,0x4D02,
                  0x4D01,0x4D00,0x4D00,0x4D00,0x4D00,0x4D00,0x4D00,0x4D02)),
    (0x4E, 0x01, (0x4E01,0x4E00,0x4E00,0x4E00,0x4E00,0x4E00,0x4E00,0x4E02,
                  0x4E01,0x4E00,0x4E00,0x4E00,0x4E00,0x4E00,0x4E00,0x4E02)),
    (0x4F, 0x01, (0x4F01,0x4F00,0x4F00,0x4F00,0x4F00,0x4F00,0x4F00,0x4F02,
                  0x4F01,0x4F00,0x4F00,0x4F00,0x4F00,0x4F00,0x4F00,0x4F02)),
    (0x50, 0x01, (0x5001,0x5000,0x5000,0x5000,0x5000,0x5000,0x5000,0x5002,
                  0x5001,0x5000,0x5000,0x5000,0x5000,0x5000,0x5000,0x5002)),
    (0x51, 0x01, (0x5101,0x5100,0x5100,0x5100,0x5100,0x5100,0x5100,0x5102,
                  0x5101,0x5100,0x5100,0x5100,0x5100,0x5100,0x5100,0x5102)),
    (0x52, 0x01, (0x5201,0x5200,0x5200,0x5200,0x5200,0x5200,0x5200,0x5202,
                  0x5201,0x5200,0x5200,0x5200,0x5200,0x5200,0x5200,0x5202)),
    (0x53, 0x02, (0x5302,0x5300,0x5300,0x5300,0x5300,0x5300,0x5300,0x5304,
                  0x5302,0x5300,0x5300,0x5300,0x5300,0x5300,0x5300,0x5304)),
    (0x54, 0x01, (0x5401,0x5400,0x5400,0x5400,0x5400,0x5400,0x5400,0x5402,
                  0x5401,0x5400,0x5400,0x5400,0x5400,0x5400,0x5400,0x5402)),
    (0x55, 0x02, (0x5502,0x5500,0x5500,0x5500,0x5500,0x5500,0x5500,0x5504,
                  0x5502,0x5500,0x5500,0x5500,0x5500,0x5500,0x5500,0x5504)),
    (0x56, 0x01, (0x5601,0x5600,0x5600,0x5600,0x5600,0x5600,0x5600,0x5602,
                  0x5601,0x5600,0x5600,0x5600,0x5600,0x5600,0x5600,0x5602)),
    (0x57, 0x02, (0x5702,0x5700,0x5700,0x5700,0x5700,0x5700,0x5700,0x5704,
                  0x5702,0x5700,0x5700,0x5700,0x5700,0x5700,0x5700,0x5704)),
    (0x58, 0x01, (0x5801,0x5800,0x5800,0x5800,0x5800,0x5800,0x5800,0x5802,
                  0x5801,0x5800,0x5800,0x5800,0x5800,0x5800,0x5800,0x5802)),
    (0x59, 0x02, (0x5902,0x5900,0x5900,0x5900,0x5900,0x5900,0x5900,0x5904,
                  0x5902,0x5900,0x5900,0x5900,0x5900,0x5900,0x5900,0x5904)),
    (0x5A, 0x01, (0x5A01,0x5A00,0x5A00,0x5A00,0x5A00,0x5A00,0x5A00,0x5A02,
                  0x5A01,0x5A00,0x5A00,0x5A00,0x5A00,0x5A00,0x5A00,0x5A02)),
    (0x5B, 0x04, (0x5B04,0x5B00,0x5B00,0x5B00,0x5B00,0x5B00,0x5B00,0x5B08,
                  0x5B04,0x5B00,0x5B00,0x5B0C,0x5B00,0x5B00,0x5B00,0x5B08)),
    (0x5C, 0x01, (0x5C01,0x5C00,0x5C00,0x5C00,0x5C00,0x5C00,0x5C00,0x5C02,
                  0x5C01,0x5C00,0x5C00,0x5C00,0x5C00,0x5C00,0x5C00,0x5C02)),
    (0x5D, 0x03, (0x5D03,0x5D00,0x5D00,0x5D00,0x5D00,0x5D00,0x5D00,0x5D06,
                  0x5D03,0x5D00,0x5D00,0x5D09,0x5D00,0x5D00,0x5D00,0x5D06)),
    (0x5E, 0x01, (0x5E00,0x5E01,0x5E00,0x5E00,0x5E00,0x5E00,0x5E00,0x5E00,
                  0x5E00,0x5E01,0x5E00,0x5E00,0x5E00,0x5E00,0x5E00,0x5E01)),
    (0x68, 0x14, (0x6900,0x6800,0x6800,0x6800,0x6800,0x6800,0x6800,0x7100,
                  0x6800,0x6800,0x6800,0x6800,0x6800,0x6800,0x6800,0x7100)),
    (0x6A, 0x0E, (0x6A0E,0x6A00,0x6A00,0x6A00,0x6A1C,0x6A00,0x6A00,0x6A2A,
                  0x6A0E,0x6A00,0x6A00,0x6A00,0x6A1C,0x6A00,0x6A00,0x6A2A)),
    (0x6B, 0x04, (0x6B04,0x6B00,0x6B00,0x6B00,0x6B08,0x6B10,0x6B00,0x6B0C,
                  0x6B04,0x6B00,0x6B00,0x6B00,0x6B08,0x6B00,0x6B00,0x6B0C)),
    (0x6C, 0x01, (0x6C01,0x6C00,0x6C00,0x6C00,0x6C02,0x6C04,0x6C00,0x6C03,
                  0x6C01,0x6C00,0x6C00,0x6C00,0x6C02,0x6C00,0x6C00,0x6C03)),
    (0x9E, 0x08, (0x9E08,0x9E08,0x9E08,0x9E08,0x9E08,0x9E08,0x9E00,0x9E08,
                  0x9E08,0x9E08,0x9E08,0x9E08,0x9E08,0x9E08,0x9E00,0x9E08)),
    (0xA3, 0x04, (0xA304,0xA300,0xA300,0xA300,0xA308,0xA310,0xA300,0xA30C,
                  0xA304,0xA300,0xA300,0xA300,0xA308,0xA300,0xA300,0xA30C)),
    )

## Text-related constants

msgtypes = (
    ("Level name",
     "Text displayed when entering a level, as Yoshi jumps in."),
    ("Standard message",
     """Text typically displayed on a chalkboard-style green background.
Used by message blocks, Kamek, minigames, and various other sources."""),
    ("File select",
     """Text displayed below the three save file icons.<br><i>Text above the
file icons is graphical and can be found in YITitle_L0.bin.</i>"""),
    ("Ending",
     """The single message that appears after Yoshi defeats Bowser and saves
Baby Luigi and the stork, which has a unique format."""),
    ("Story intro",
     "Text displayed during the story sequences before the title screen."),
    ("Credits",
     "Text displayed during and after the credits."),
    )

sma3char = [
    "à", "â", "ç", "è", "é", "ê", "î", "ô", #00-07
    "ù", "û", "/", "œ", None, None, None, None, #08-0F
    "ä", "ö", "ü", "ß", "Ä", "Ö", "Ü", None, #10-17
    "\{Rcrop0}", "\{Rcrop1}", "\{Abutton0}", "\{Abutton1}",
    "\{Bbutton0}", "\{Bbutton1}", "\{Lcrop0}", "\{Lcrop1}", #18-1F
    "\{select0}", "\{select1}", "\{select2}", "\{Lbutton0}",
    "\{Lbutton1}", "\{Lbutton2}", ":", ";", #20-27
    "\{Rbutton0}", "\{Rbutton1}", "\{Rbutton2}", "'",
    "\{upoutline}", "\{left}", "\{right}", "\{up}", #28-2F
    "\{down}", "\{start0}", "\{start1}", "\{start2}",
    "\{upcloud0}", "\{upcloud1}", "=", ",", #30-37
    "\{e_}", "\{i_}", "\{t_}", "\{r_}", "\{h_}", "\{f_}", "\{n_}", ".", #38-3F
    "À", "Â", "Ç", "È", "É", "Ê", "Î", "Ô", #40-47
    "Ú", "Ù", "Ï", "ï", "Ë", "Û", "Á", "Í", #48-4F
    "Ñ", "Ó", "Ì", "Ò", "ë", "ò", "á", "í", #50-57
    "ñ", "ó", "ì", "º", "ª", "¡", "¿", "ú", #58-5F
    None, None, None, None, None, None, None, None, #60-67
    None, None, None, None, None, None, None, None, #68-6F
    None, None, None, None, None, None, None, None, #70-77
    None, None, None, None, None, None, None, None, #78-7F
    None, None, None, None, None, None, None, None, #80-87
    None, None, None, None, None, None, None, None, #88-8F
    None, None, None, None, None, None, None, None, #90-97
    None, None, None, None, None, None, None, None, #98-9F
    "0", "1", "2", "3", "4", "5", "6", "7", #A0-A7
    "8", "9", "A", "B", "C", "D", "E", "F", #A8-AF
    "G", "H", "I", "J", "K", "L", "M", "N", #B0-B7
    "O", "P", "Q", "R", "S", "T", "U", "V", #B8-BF
    "W", "X", "Y", "Z", "『", "』", "?", "!", #C0-C7
    "、", "-", "\{dpad0}", "\{dpad1}", "\{...}", "。", "~", "\{, }", #C8-CF
    " ", "“", "”", "·",
    "\{triright}", "\{yoshi0}", "\{yoshi1}", "\{times}", #D0-D7
    "a", "b", "c", "d", "e", "f", "g", "h", #D8-DF
    "i", "j", "k", "l", "m", "n", "o", "p", #E0-E7
    "q", "r", "s", "t", "u", "v", "w", "x", #E8-EF
    "y", "z", "\{trileft}", "\{. }",
    "\{?cloud0}", "\{?cloud1}", "\{star0}", "\{star1}", #F0-F7
    "\{!switch0}", "\{!switch1}", "\{downoutline}", "\{heartL0}",
    "\{heartL1}", "\{heartR0}", "\{heartR1}", None, #F8-FF
    ]

sma3char_lookup = {}  # dict to convert character strings to IDs
sma3char_maxlen = 1   # max character string length
for i, charstr in enumerate(sma3char):
    if charstr is not None:
        sma3char_lookup[charstr] = i
        if charstr[0] == "\\" and len(charstr) > sma3char_maxlen:
            sma3char_maxlen = len(charstr)

msgcommands = {
    "Level name": [
        (0xFE, "Set Y/X"),
        (0xFF, "Set X only"),
        ],
    "Standard message": [
        (0x01, "Erase line at y=0"),
        (0x02, "Erase line at y=10"),
        (0x03, "Erase line at y=20"),
        (0x04, "Erase line at y=30"),
        (0x05, "Start line at y=0"),
        (0x06, "Start line at y=10"),
        (0x07, "Start line at y=20"),
        (0x08, "Start line at y=30"),
        (0x0A, "Wait for down/A (sound/arrow)"),
        (0x0E, "Erase + start line at y=40"),
        (0x0F, "Wait for down/A"),
        (0x11, "Scroll down 1px"),
        (0x12, "Scroll down 2px"),
        (0x13, "Scroll down 3px"),
        (0x14, "Scroll down 4px"),
        (0x30, "Reset scale"),
        (0x31, "Horiz/vert scale 2x"),
        (0x32, "Horiz/vert scale 3x"),
        (0x33, "Horiz/vert scale 4x"),
        (0x34, "Vertical scale 1x"),
        (0x35, "Vertical scale 2x"),
        (0x36, "Vertical scale 3x"),
        (0x37, "Vertical scale 4x"),
        (0x38, "Horizontal scale 1x"),
        (0x39, "Horizontal scale 2x"),
        (0x3A, "Horizontal scale 3x"),
        (0x3B, "Horizontal scale 4x"),
        (0x3D, "Lives hundreds digit"),
        (0x3E, "Lives tens digit"),
        (0x3F, "Lives ones digit"),
        (0x50, "Activate menu (death)"),
        (0x51, "Activate menu (Flip Cards)"),
        (0x52, "Activate menu (egg config)"),
        (0x60, "Large image"),
        ],
    "File select": [
        (None, "Set X/Y"),
        ],
    "Ending": [
        (0x00, "Restart current line"),
        (0x0A, "Start new line"),
        ],
    "Story intro": [
        (0x00, "Single 1x scale character"),
        (0x01, "(skip byte)"),
        (0x02, "Set Y (value*2)"),
        (0x03, "Set X"),
        (0x04, "Scale 2x, remove line gap"),
        (0x05, "Single 2x scale character"),
        (0x31, "Scale 2x, remove line gap"),
        ],
    "Credits": [
        (0x00, "Single character"),
        (0x01, "(skip byte)"),
        (0x02, "Set Y (value*2)"),
        (0x03, "Set X"),
        ],
    }
